GET http://localhost:8080/api/data/triennale/21-22/teacher 

###
GET http://localhost:8080/api/data/triennale/21-22/class

###
GET http://localhost:8080/api/data/triennale/21-22/calendar/2


###
# MAGISTRALE
GET http://localhost:8080/api/data/magistrale/21-22/teacher

###
GET http://localhost:8080/api/data/magistrale/21-22/class

###
GET http://localhost:8080/api/data/magistrale/21-22/calendar/2